apiVersion: v1
kind: Service
metadata:
  name: zookepper-nodeport-service
spec:
  type: NodePort
  selector:
    zooType: "common"
  ports: 
    - name: client
      port: 2181
      targetPort: 2181
      protocol: TCP

